# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-08 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.EmailTemplate')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.Subscriber')),
            ],
        ),
    ]
